from .cifar10_model import get_cifar10_pretrained_models_with_features, get_cifar10_transfer_models
from .imagenet_model import get_imagenet_pretrained_models_with_features, get_imagenet_transfer_models
from .model import test_model, test_models